[package]
name = "blink"
version = "0.1.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
edition = "2018"

[profile.release]
debug = true
lto = true
opt-level = "z"

[dependencies.ruduino]
path = "./ruduino"
